version: "3"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "8020:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "8021:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  api:
    image: jdromero9402/mlops_inference_diabetes:v2
    ports:
      - "8015:80" 
      # Mapea el puerto 80 del contenedor al puerto 8989 del host.
    environment:
      - MODELS_DIR=/app/models
      - MLFLOW_TRACKING_URI=http://10.43.100.99:8003
      - MODEL_NAME=property-market-model
      - MODEL_STAGE=prod
    volumes:
      - './models:/app/models'
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]