version: "3"
services:
  mysql-db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: training
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8005:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: